name: Beeminder Commit Tracker

on:
  # 允许手动运行 (用于测试)
  workflow_dispatch:
    inputs:
      local_hour:
        description: '任务本地小时 (14 或 23)'
        required: true
        default: '14'
      check_start_hour:
        description: '检查窗口开始小时 (12 或 23)'
        required: true
        default: '12'
      check_end_minute:
        description: '检查窗口结束分钟 (00 或 30/50)' # 修正描述
        required: true
        default: '00'
        
  # 使用 schedule 事件来定义定时任务
  schedule:
    # -------------------------------------------------------------
    # UTC+8 14:00 任务 (检查 12:00-14:00) = UTC 06:00
    - cron: '0 6 * * *'
    
    # UTC+8 23:35 任务 (检查 23:00-23:30) = UTC 15:35
    - cron: '35 15 * * *'

jobs:
  run_beeminder_check:
    runs-on: ubuntu-latest
    
    env:
      BEEMINDER_USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
      BEEMINDER_AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
      BEEMINDER_GOAL_NAME: ${{ secrets.BEEMINDER_GOAL_NAME }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Determine local time and run script
      run: |
        # 1. 检查触发事件类型 (手动触发 vs. 定时触发)
        TRIGGER_EVENT="${{ github.event_name }}"
        
        if [ "$TRIGGER_EVENT" = "workflow_dispatch" ]; then
          # --- 逻辑 A: 手动触发 (直接使用用户输入的参数) ---
          LOCAL_HOUR="${{ github.event.inputs.local_hour }}"
          CHECK_START_HOUR="${{ github.event.inputs.check_start_hour }}"
          CHECK_END_MINUTE="${{ github.event.inputs.check_end_minute }}"
          
          echo "✅ 触发模式: 手动。使用输入参数:"
          echo "   本地小时: ${LOCAL_HOUR}"
          echo "   检查开始小时: ${CHECK_START_HOUR}"
          echo "   检查结束分钟: ${CHECK_END_MINUTE}"

        elif [ "$TRIGGER_EVENT" = "schedule" ]; then
          # --- 逻辑 B: 定时触发 (根据 UTC 时间匹配任务) ---
          
          UTC_HOUR=$(date -u +%H)
          UTC_MINUTE=$(date -u +%M)

          # 2. 根据 UTC 时间确定要执行的本地任务参数
          if [ "$UTC_HOUR" -eq 6 ]; then
            # ✅ 匹配 UTC+8 14:xx 任务 (UTC 06:xx)
            # 检查窗口：12:00 到 14:00
            LOCAL_HOUR=14
            CHECK_START_HOUR=12
            CHECK_END_MINUTE=00
          elif [ "$UTC_HOUR" -eq 15 ]; then
            # ✅ 匹配 UTC+8 23:xx 任务 (UTC 15:xx)
            # 检查窗口：23:00 到 23:30 (允许 23:35 左右启动)
            LOCAL_HOUR=23
            CHECK_START_HOUR=23
            CHECK_END_MINUTE=30 # 新的结束分钟
          else
            # 允许 Action 在设定的 UTC 小时内启动（即使有延迟）
            echo "Error: Job triggered at an unexpected UTC time ($UTC_HOUR:$UTC_MINUTE). Skipping."
            exit 1
          fi
          echo "✅ 触发模式: 定时。匹配 UTC 任务 $UTC_HOUR:$UTC_MINUTE，检查窗口 ${CHECK_START_HOUR}:00 - ${LOCAL_HOUR}:${CHECK_END_MINUTE}"
          
        else
          # --- 逻辑 C: 应对其他触发事件 ---
          # 只需要警告，不再 exit 0 或 exit 1
          echo "Warning: Job triggered by unexpected event ($TRIGGER_EVENT). Running with default parameters."
          # 传入默认参数，让 Python 脚本自行判断是否执行
          LOCAL_HOUR=14
          CHECK_START_HOUR=12
          CHECK_END_MINUTE=00
        fi
        
        # 3. 运行 Python 脚本
        # 传入参数: 当前本地小时 | 检查开始小时 | 检查结束分钟
        python beeminder.py "$LOCAL_HOUR" "$CHECK_START_HOUR" "$CHECK_END_MINUTE"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}